CREATE TABLE TIPO_CUENTAS (
    TCTA_ID          NUMBER(2) PRIMARY KEY,
    TCTA_NOMBRE      VARCHAR2(50) NOT NULL
);

CREATE TABLE PERSONAS (
    PER_ID              NUMBER(12) PRIMARY KEY,
    PER_NOMBRE          VARCHAR2(50) NOT NULL,
    PER_GENERO          VARCHAR2(1) NOT NULL,
    PER_EDAD            NUMBER(3) NOT NULL,
    PER_IDENTIFICACION  VARCHAR2(15) NOT NULL,
	PER_DIRECCION       VARCHAR2(50) NOT NULL,
    PER_TELEFONO        VARCHAR2(20) NOT NULL,
    PER_FE_CREA         DATE NOT NULL,
    PER_FE_ACTUALIZA    DATE
);

CREATE TABLE CLIENTES (
    CLI_ID              NUMBER(12) PRIMARY KEY,
    CLI_PER_ID          NUMBER(12) NOT NULL,
    CLI_CONTRA          VARCHAR2(200) NOT NULL,
    CLI_ESTADO          CHAR(1) NOT NULL,
    CLI_FE_CREA         DATE NOT NULL,
	CLI_FE_ACTUALIZA    DATE,
    CONSTRAINT CLI_PER_ID_FK FOREIGN KEY ( CLI_PER_ID )
        REFERENCES PERSONAS ( PER_ID )
);


CREATE TABLE CUENTAS (
    CTA_ID              NUMBER(12) PRIMARY KEY,
	CTA_CLI_ID			NUMBER(12) NOT NULL,
    CTA_NUM_CUENTA      VARCHAR2(10) NOT NULL,
    CTA_TIPO_CUENTA     NUMBER(2) NOT NULL,
    CTA_SALDO_TOTAL   NUMBER(20,2) NOT NULL,
	CTA_ESTADO          CHAR(1) NOT NULL,
    CTA_FE_CREA         DATE NOT NULL,
	CTA_FE_ACTUALIZA    DATE,
	CONSTRAINT CTA_CLI_ID_FK FOREIGN KEY ( CTA_CLI_ID )
        REFERENCES CLIENTES ( CLI_ID ),
    CONSTRAINT CTA_TIPO_CUENTA_FK FOREIGN KEY ( CTA_TIPO_CUENTA )
        REFERENCES TIPO_CUENTAS ( TCTA_ID )
);

CREATE TABLE MOVIMIENTOS (
    MOV_ID          NUMBER(12) PRIMARY KEY,
    MOV_FECHA       DATE NOT NULL,
    MOV_VALOR       NUMBER(20,2) NOT NULL,
	MOV_SALDO_INI   NUMBER(20,2) NOT NULL,
    MOV_SALDO_FIN   NUMBER(20,2) NOT NULL,
	MOV_CTA_ID      NUMBER(12) NOT NULL,
    MOV_ESTADO      CHAR(1) NOT NULL,
    CONSTRAINT MOV_CTA_ID_FK FOREIGN KEY ( MOV_CTA_ID )
        REFERENCES CUENTAS ( CTA_ID )
);

CREATE SEQUENCE PER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CLI_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CTA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MOV_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO TIPO_CUENTAS VALUES (1, 'Ahorros');
INSERT INTO TIPO_CUENTAS VALUES (2, 'Corriente');

commit;


-- ELIMINAR TODO
--DROP TABLE TIPO_CUENTAS CASCADE CONSTRAINTS;
--DROP TABLE PERSONAS CASCADE CONSTRAINTS;
--DROP TABLE CLIENTES CASCADE CONSTRAINTS;
--DROP TABLE CUENTAS CASCADE CONSTRAINTS;
--DROP TABLE MOVIMIENTOS CASCADE CONSTRAINTS;
--drop sequence PER_SEQ;
--drop sequence CLI_SEQ;
--drop sequence CTA_SEQ;
--drop sequence MOV_SEQ;